# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Syncthing
tagline:          'Documentation'
description:      ''
url:              https://syncthing.net/
baseurl:          ''

author:
  name:           'Jakob Borg'
  url:            https://twitter.com/syncthing
  email: info@syncthing.net

# Custom vars
version:          2.1.0

redcarpet:
  extensions: ["autolink", "with_toc_data"]

collections:
  dev:
    output: true
  intro:
    output: true
  users:
    output: true
  rest:
    output: false

defaults:
  -
    scope:
      path: ""
      type: "dev"
    values:
      layout: "page"
      weight: 5
      nav: true
  -
    scope:
      path: ""
      type: "intro"
    values:
      layout: "page"
      weight: 5
      nav: true
  -
    scope:
      path: ""
      type: "users"
    values:
      layout: "page"
      weight: 5
      nav: true
